// examples/react-testapp/src/App.tsx
/**
 * Playground — add components below to test them during development.
 *
 * Import from '@telesign/boreal-react' and render components here.
 * Run: pnpm dev:pack (from the root of the monorepo) to start the pipeline
 * and open this page in the browser.
 *
 * Available themes for data-theme: connect | engage | protect | proximus
 * Set the theme on <body> in index.html.
 */
import './App.css';

function App() {
  return (
    <main>
      <h1>Boreal DS — React Playground</h1>

      {/* Add components below */}
    </main>
  );
}

export default App;

// examples/vue-testapp/src/App.vue
<script setup lang="ts">
/**
 * Playground — add components below to test them during development.
 *
 * Import from '@telesign/boreal-vue' and render components here.
 * Run: pnpm dev:pack:vue (from the root of the monorepo) to start the pipeline
 * and open this page in the browser.
 *
 * Available themes for data-theme: connect | engage | protect | proximus
 * Set the theme on <body> in index.html.
 */
</script>

<template>
  <main>
    <h1>Boreal DS — Vue Playground</h1>

    <!-- Add components below -->
  </main>
</template>
